proyecto/apps/productos/urls.py
from django.urls import path
from .import views

app_name = 'productos'

urlpatterns = [
  path('listar/', views.ListarProductos, name='listar'),
  path('detalle/<int:pk>', views.DetalleProducto, name='detalle'),
]

proyecto/proyecto/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth
from .import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.Home, name='login'),
    path('login/',auth.LoginView.as_view(template_name='usuarios/login.html'), name='login'),
    path('logout/',auth.LogoutView.as_view(), name='logout'),

    #path direccion a las app
    path('productos/', include('apps.productos.urls'))
]
#pbkdf2_sha256$180000$7iOh2ufWWv7E$Y57+Zoe6tWIR4aMsxr1YZ8D2j2ZwjUfZ/KUQcWnUwP4=

proyecto/apps/core/models.py
from django.db import models
from django.db.models.fields import DateTimeField

# Create your models here.

class TimeModels(models.Model):
    creado = DateTimeField(auto_now_add=True,
                            verbose_name=u'creado',
                            help_text=u'fecha de creacion')
    modificado = models.DateTimeField(auto_now_add=True,
                            verbose_name=u'modificado',
                            help_text=u'fecha de modificacion')

    class Meta():
        abstract = True

proyecto/apps/genericos/models.py
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.
class Rubro(models.Model):
    nombre = models.CharField(max_length=50)
    
    def __str__(self):
        return self.nombre

class SubRubro(models.Model):
    nombre = models.CharField(max_length=50)
    rubro = models.ForeignKey(Rubro, related_name='mi_rubro', on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nombre
    

proyecto/apps/productos/models.py
from django.db import models
from apps.core.models import TimeModels
from apps.genericos.models import SubRubro
# Create your models here.

class Producto(TimeModels):
    nombre = models.CharField(max_length=30)
    precio = models.DecimalField(max_digits=8, decimal_places=2)
    stock = models.IntegerField(default=0)
    subrubro = models.ForeignKey(SubRubro, on_delete=models.SET_NULL, null= True)

    def __str__(self):
        return self.nombre
    

proyecto/apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Usuario(AbstractUser):
    pass

proyecto/apps/genericos/views.py
from django.shortcuts import render

# Create your views here.

proyecto/apps/productos/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from .models import Producto

# Create your views here.

@login_required
def ListarProductos(request):
    # declara un diccionario que por convencion se llama context
    context = {}
    #Buscar todos los productos
    #Producto.objects.all() se transforma en:
    # SELECT * FROM Producto
    todos = Producto.objects.all() # ORM de django
    # guarda en el diccionario context los productos y se los pasa al template
    context['productos'] = todos
    # Pasarlos al template con el context al final del return para que me retorne la lista completa en el 
    # template
    return render(request, 'productos/listar.html', context)

@login_required
def DetalleProducto(request, pk):
    context = {}
    #SELECT * FROM PRODUCTOS WHERE id = pk
    objeto = Producto.objects.get(id = pk) # ORM de django
    context['producto'] = objeto
    return render(request, 'productos/detalle.html', context)

#ORM PRINCIPALES

# NOMBRE_CLASE.objects.all() "TRAE TODOS"
# NOMBRE_CLASE.objects.get() "TRAE SOLO EL QUE CUMPLA LA CONDICION"
# NOMBRE_CLASE.objects.filter() "TRAE TODOS LOS QUE CUMPLAN LA CONDICION"

proyecto/proyecto/views.py
from django.shortcuts import render

def Home(request):
    return render(request, 'index.html')

proyecto/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" src="{% static 'css/all.min.css' %}">
    
    <!--FOOTER-->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!--FOOTER-->
    <title>INFORMATORIO</title>
</head>
<body>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script> 
    <script src="{% static 'js/all.min.js' %}"></script> 
    
    
        
        {% if user.is_authenticated %}

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Sistema de encuesta</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Dropdown
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                  </div>
                </li>
                <li class="nav-item">
                  <a class="nav-link disabled" href="#">Disabled</a>
                </li>
              </ul>
              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <span>Bienvenido Sr/sra.&nbsp; {{user.username}} &nbsp;</span>
                <a href="{% url 'logout' %}" class="btn btn-primary my-2 my-sm-0">Cerrar Sesión</a>
              </form>
            </div>
          </nav>

        
       <!-- <span>{{user.username}}</span>
        <a class="btn btn-primary" href="{% url 'logout' %}"> Cerrar sesión</a>-->
        
        {% endif %}
        
        <div class="container">
    {% block contenido %}
    

    {% endblock contenido %}
</div>
<!------ Include the above in your HEAD tag ---------->
{% if user.is_authenticated %}
<!-- Footer -->

	<!-- ./Footer -->
    {% endif %}
    
</div>
</body>
</html>

proyecto/templates/index.html
{% extends 'base.html' %}

{% load static %}


{% block contenido %}

{% if user.is_authenticated %}
<h1>Bienvenidos al menu del sistema</h1>
<div class="col container">
    <div class="row">
        <a href="{% url 'login' %}">Ir al login</a>
    </div>
    <div class="row">
        <a href="{% url 'productos:listar' %}">listar producto</a>
    </div>
</div>
{% else %}
<a href="{% url 'login' %}"> ir al login</a>

{% endif %}

<br>


{% endblock contenido %}

proyecto/templates/productos/detalle.html
{% extends 'base.html' %}
{% load static %}


{% block contenido %}
<h1>Detalle de Producto seleccionado {{producto.nombre}}</h1>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Precio</th>
            <th>Stock</th>
            <th>Subrubro</th>
            <th>rubro</th>
        </tr>
    </thead>
    <tbody>
        
        <tr>
            <td>{{producto.precio}}</td>
            <td>{{producto.stock}}</td>
            <td>{{producto.subrubro}}</td>
            <td>{{producto.subrubro.rubro}}</td>
        </tr>
        
    </tbody>
</table>
<div class="col">
    <div class="row">
        <a class="btn btn-primary" href="{% url 'productos:listar' %}">Volver a Productos</a>
    </div>
</div>


{% endblock contenido %}

proyecto/templates/productos/listar.html
{% extends 'base.html' %}
{% load static %}


{% block contenido %}

<h1>Listado de productos</h1>

<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Nombre</th>
            
            <th>Acción</th>
        </tr>
    </thead>
    <tbody>
        {% if productos %}
        {% for p in productos %}
        <tr>
            <td scope="row">{{p.nombre}}</td>
            <td>
                <a href="{% url 'productos:detalle' p.id %}"  type="button" class="btn btn-warning" data-toggle="tooltip" data-placement="right" title="Ver detalle">
                    <i class="fas fa-eye"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
        {% endif %}
    </tbody>
</table>

<a href="{% url 'home' %}">ir al home</a>
{% endblock contenido %}

proyecto/templates/ruleta/ruleta.html
<html>
    <head>
        <title>Code Wheel</title>
        <script src='Winwheel.js'></script>
    </head>
    <body>
        <canvas id='canvas' width='880' height='300'>
            Canvas not supported, use another browser.
        </canvas>
        <script>
            let theWheel = new Winwheel({
                'numSegments'  : 8,         // Number of segments
                'outerRadius'  : 212,       // The size of the wheel.
                'centerX'      : 217,       // Used to position on the background correctly.
                'centerY'      : 219,
                'textFontSize' : 28,        // Font size.
                'segments'     :            // Definition of all the segments.
                [
                   {'fillStyle' : '#eae56f', 'text' : 'Prize 1'},
                   {'fillStyle' : '#89f26e', 'text' : 'Prize 2'},
                   {'fillStyle' : '#7de6ef', 'text' : 'Prize 3'},
                   {'fillStyle' : '#e7706f', 'text' : 'Prize 4'},
                   {'fillStyle' : '#eae56f', 'text' : 'Prize 5'},
                   {'fillStyle' : '#89f26e', 'text' : 'Prize 6'},
                   {'fillStyle' : '#7de6ef', 'text' : 'Prize 7'},
                   {'fillStyle' : '#e7706f', 'text' : 'Prize 8'}
                ],
                'animation' :               // Definition of the animation
                {
                    'type'     : 'spinToStop',
                    'duration' : 5,
                    'spins'    : 8,
                    'callbackFinished' : alertPrize
                }
            });
 
            // Called when the animation has finished.
            function alertPrize(indicatedSegment)
            {
                // Do basic alert of the segment text.
                alert("You have won " + indicatedSegment.text);
            }
        </script>
    </body>
</html>

proyecto/templates/usuarios/login.html
{% extends 'base.html' %}

{% block contenido %}

<!------ <form method="POST"> {% csrf_token %}
        {{form.errors}}
        <input type="text" name="username" placeholder="Usuario">
        <input type="password" name="password" placeholder="Contraseña">

        <input type="submit" value="Enviar>">
    </form>---------->

    <!------ Include the above in your HEAD tag ---------->
    
    <div class="container" style="margin-bottom: 100px;">
        <br>
        <br>
    <div class="container h-80">
    <div class="row align-items-center h-100">
        <div class="col-3 mx-auto" style="box-shadow: 2px 2px 6px white; padding: 2rem;">
            <div class="text-center">
                <img id="profile-img" class="rounded-circle profile-img-card" src="https://i.imgur.com/6b6psnA.png" />
                <p id="profile-name" class="profile-name-card"></p>
                
                <form method="POST"  class="form-signin">
                    {% csrf_token %}
                    {{form.errors}}
                    <input type="text" name="username" id="inputPassword" class="form-control form-group" placeholder="Usuario" required autofocus>
                    <br>
                    <input type="password" name="password" id="inputPassword" class="form-control form-group" placeholder="Contraseña" required autofocus>
                    <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Ingresar</button>
                </form>
           
            </div>
        </div>
    </div>
</div>
</div>

{% endblock contenido %}